### ISSUE TITLE
NPM Install failed

### ISSUE THREAD

**Issue by as3mbus** [nukeop/nuclear-rewrite#1]
![nuclear error](https://user-images.githubusercontent.com/16043293/31042108-e01496d4-a5ca-11e7-90a0-97d30cd99a60.png)
[npm-debug.log](https://github.com/nukeop/nuclear-rewrite/files/1346092/npm-debug.log)

hey it seems like there are some error when i run "npm install" is there anything i can do about it ?

**Comment by nukeop** [comment]
Looks like there's a problem with your network and the connection timed out.

**Comment by as3mbus** [comment]
kay it work now. but it seems the warning stays. i also tried running npm start but it still not working for me. 
tried to open the localhost with it's designated port when it runs. it shows up as error and "cannot get / "as a content
thx 4 replying as usual :)

**Comment by nukeop** [comment]
The warning is fine, there are some optional dependencies that may or may not be installed depending on the operating system. For example mpris/dbus only gets installed on GNU/Linux systems.
Try running `npm run watch` first, then after webpack build the scripts run `npm run electron` in another terminal tab (so they run in parallel). This should start the dev version.

**Comment by as3mbus** [comment]
![image](https://user-images.githubusercontent.com/16043293/31055121-47519454-a6e9-11e7-8e1e-5e5d46c4a936.png)
it display error on the npm run electron command

**Comment by nukeop** [comment]
There is a problem with some version dbus not cooperating with certain versins of node. To fix that, try doing the following:

- `npm install electron-rebuild`
- `./node_modules/.bin/electron-rebuild`

And then `npm run electron` as usual. This should rebuild the problematic module to work with your version of node.

**Comment by as3mbus** [comment]
kay it work. it display electron with debugging state. well it seems most of it aint working right now on my machine. but it alrdy give me an awesome looks on how it'll become once it done. keep up the great work

**Comment by nukeop** [comment]
Great, thanks for the feedback.
